export enum GraphEvent {
  click = 'click',
  dblclick = 'dblclick',
  mouseenter = 'mouseenter',
  mousemove = 'mousemove',
  mouseout = 'mouseout',
  mouseover = 'mouseover',
  mouseleave = 'mouseleave',
  mousedown = 'mousedown',
  mouseup = 'mouseup',
  contextmenu = 'contextmenu',
  dragstart = 'dragstart',
  drag = 'drag',
  dragend = 'dragend',
  dragenter = 'dragenter',
  dragleave = 'dragleave',
  drop = 'drop',
  keydown = 'keydown',
  keyup = 'keyup',
  wheel = 'wheel',
  touchstart = 'touchstart',
  touchmove = 'touchmove',
  touchend = 'touchend',
}
export enum GraphNodeEvent {
  nodeClick = 'node:click',
  nodeDblclick = 'node:dblclick',
  nodeMouseenter = 'node:mouseenter',
  nodeMousemove = 'node:mousemove',
  nodeMouseout = 'node:mouseout',
  nodeMouseover = 'node:mouseover',
  nodeMouseleave = 'node:mouseleave',
  nodeMousedown = 'node:mousedown',
  nodeMouseup = 'node:mouseup',
  nodeDragstart = 'node:dragstart',
  nodeDrag = 'node:drag',
  nodeDragend = 'node:dragend',
  nodeDragenter = 'node:dragenter',
  nodeDragleave = 'node:dragleave',
  nodeDragover = 'node:dragover',
  nodeDrop = 'node:drop',
  nodeTouchstart = 'node:touchstart',
  nodeTouchmove = 'node:touchmove',
  nodeTouchend = 'node:touchend',
  nodeContextmenu = 'node:contextmenu',
}

export enum GraphEdgeEvent {
  edgeClick = 'edge:click',
  edgeDblclick = 'edge:dblclick',
  edgeMouseenter = 'edge:mouseenter',
  edgeMousemove = 'edge:mousemove',
  edgeMouseout = 'edge:mouseout',
  edgeMouseover = 'edge:mouseover',
  edgeMouseleave = 'edge:mouseleave',
  edgeMousedown = 'edge:mousedown',
  edgeMouseup = 'edge:mouseup',
  edgeDragenter = 'edge:dragenter',
  edgeDragleave = 'edge:dragleave',
  edgeDragover = 'edge:dragover',
  edgeDrop = 'edge:drop',
  edgeContextmenu = 'edge:contextmenu',
}
export enum GraphCanvasEvent {
  canvasClick = 'canvas:click',
  canvasDblclick = 'canvas:dblclick',
  canvasMouseenter = 'canvas:mouseenter',
  canvasMousemove = 'canvas:mousemove',
  canvasMouseout = 'canvas:mouseout',
  canvasMouseover = 'canvas:mouseover',
  canvasMouseleave = 'canvas:mouseleave',
  canvasMousedown = 'canvas:mousedown',
  canvasMouseup = 'canvas:mouseup',
  canvasContextmenu = 'canvas:contextmenu',
  canvasDragstart = 'canvas:dragstart',
  canvasDrag = 'canvas:drag',
  canvasDragend = 'canvas:dragend',
  canvasDragenter = 'canvas:dragenter',
  canvasDragleave = 'canvas:dragleave',
  canvasDrop = 'canvas:drop',
  canvasTouchstart = 'canvas:touchstart',
  canvasTouchmove = 'canvas:touchmove',
  canvasTouchend = 'canvas:touchend',
}

export enum GraphTimingEvent {
  beforerender = 'beforerender',
  afterrender = 'afterrender',
  beforeadditem = 'beforeadditem',
  afteradditem = 'afteradditem',
  beforeremoveitem = 'beforeremoveitem',
  afterremoveitem = 'afterremoveitem',
  beforeupdateitem = 'beforeupdateitem',
  afterupdateitem = 'afterupdateitem',
  beforeitemvisibilitychange = 'beforeitemvisibilitychange',
  afteritemvisibilitychange = 'afteritemvisibilitychange',
  beforeitemstatechange = 'beforeitemstatechange',
  afteritemstatechange = 'afteritemstatechange',
  beforeitemrefresh = 'beforeitemrefresh',
  afteritemrefresh = 'afteritemrefresh',
  beforeitemstatesclear = 'beforeitemstatesclear',
  afteritemstatesclear = 'afteritemstatesclear',
  beforemodechange = 'beforemodechange',
  aftermodechange = 'aftermodechange',
  beforelayout = 'beforelayout',
  afterlayout = 'afterlayout',
  beforegraphrefreshposition = 'beforegraphrefreshposition',
  aftergraphrefreshposition = 'aftergraphrefreshposition',
  beforegraphrefresh = 'beforegraphrefresh',
  aftergraphrefresh = 'aftergraphrefresh',
  beforeanimate = 'beforeanimate',
  afteranimate = 'afteranimate',
  beforecreateedge = 'beforecreateedge',
  aftercreateedge = 'aftercreateedge',
  beforecollapseexpandcombo = 'beforecollapseexpandcombo',
  aftercollapseexpandcombo = 'aftercollapseexpandcombo',
  graphstatechange = 'graphstatechange',
  afteractivaterelations = 'afteractivaterelations',
  nodeselectchange = 'nodeselectchange',
  itemcollapsed = 'itemcollapsed',
  tooltipchange = 'tooltipchange',
  wheelzoom = 'wheelzoom',
  viewportchange = 'viewportchange',
  dragnodeend = 'dragnodeend',
  stackchange = 'stackchange',
}
export enum TimeBarTimeEvent {
  valuechange = 'valuechange',
  timebarstartplay = 'timebarstartplay',
  timebarendplay = 'timebarendplay',
}
export enum TooltipEvent {
  tooltipchange = 'tooltipchange',
}
